plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT'
    id 'com.diffplug.eclipse.apt' version '3.42.2'
}

repositories {
    maven { url = 'https://maven.nucleoid.xyz' }
}

processResources {
    inputs.property "stonks_version", rootProject.stonks_version

    filesMatching("fabric.mod.json") {
        expand "stonks_version": rootProject.stonks_version
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$rootProject.minecraft_version"
    api "net.fabricmc:fabric-loader:${rootProject.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_version"
    implementation include("eu.pb4:sgui:$rootProject.sgui_version")
    implementation include("eu.pb4:common-economy-api:$rootProject.common_economy_version") {
        exclude group: 'net.fabricmc'
    }
    api include(project(':core'))
    api include(naharaToolkit('nahara-common-tasks'))
    api include(naharaToolkit('nahara-common-configurations'))
}
