org.gradle.jvmargs=-Xmx1G

# Stonks
stonks_version=2.0.0+26.1
maven_group=me.nahkd

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# Fabric Mod Dependencies
nahara_toolkit_version=b6ff2e287b
fabric_version=0.144.1+26.1
common_economy_version=1.1.1
sgui_version=2.0.0-beta.2+26.1
