org.gradle.jvmargs=-Xmx1G

# Stonks
stonks_version=2.0.0+1.21
maven_group=me.nahkd

# Fabric Properties
# check these on https://fabricmc.net/develop
# Loader 0.15.0 includes MixinExtras, pretty based indeed
minecraft_version=25w15a
yarn_mappings=25w15a+build.3
loader_version=0.16.13

# Spigot Plugin Dependencies
# <Not available yet>

# Fabric Mod Dependencies
nahara_toolkit_version=b6ff2e287b
fabric_version=0.119.10+1.21.6
common_economy_version=1.1.1
sgui_version=1.9.0+1.21.5
