site_name: Stonks Documentations
site_url: https://nahkd123.github.io/stonks/
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
