dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'
    api naharaToolkit('nahara-common-tasks')
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'
}

processResources {
    inputs.property "version", rootProject.stonks_version
    filesMatching('fabric.mod.json') {
        expand "version": rootProject.stonks_version
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
