dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    api naharaToolkit('nahara-common-tasks')
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'
    compileOnly annotationProcessor('com.google.auto.service:auto-service:1.1.1')
    implementation 'com.mojang:datafixerupper:8.0.16'
    implementation 'com.github.nahkd123:transporter:1.0.2'
    implementation 'com.github.nahkd123:tableschema:1.0.0'
}

processResources {
    inputs.property "version", rootProject.stonks_version
    filesMatching('fabric.mod.json') {
        expand "version": rootProject.stonks_version
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
