package io.github.nahkd123.stonks.utils.net;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.SocketChannel;
import java.util.Queue;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.function.Consumer;

public abstract class Connection {
	public static final short KIND_REQUEST = 0;
	public static final short KIND_RESPONSE_SUCCEED = 1;
	public static final short KIND_RESPONSE_FAILED = 2;
	public static final short KIND_NOTIFY = 3;

	private static final int READMODE_HEADER = 0;
	private static final int READMODE_BODY = 1;

	private ByteBuffer readBuffer;
	private int readMode = READMODE_HEADER;
	private short frameKind;
	private short bodySize;
	private int messageId;
	private long requestId;

	private ByteBuffer writeBuffer;
	private Queue<OutgoingFrame> writeQueue = new ConcurrentLinkedQueue<>();

	public Connection() {
		this.readBuffer = ByteBuffer.allocate(32767).limit(16);
		this.writeBuffer = ByteBuffer.allocate(32767).limit(0);
	}

	/**
	 * <p>
	 * Called when received a frame from peer.
	 * </p>
	 * 
	 * @param kind      The kind of frame. Either of {@link #KIND_REQUEST},
	 *                  {@link #KIND_RESPONSE_SUCCEED},
	 *                  {@link #KIND_RESPONSE_FAILED} or {@link #KIND_NOTIFY}.
	 * @param messageId The ID of message. Message IDs are well-known between peers.
	 * @param requestId The request ID. This is generated by request peer.
	 * @param buffer    The buffer to read from.
	 */
	protected abstract void receiveFrame(short kind, int messageId, long requestId, ByteBuffer buffer);

	protected abstract boolean shouldKeepRunning();

	/**
	 * <p>
	 * Called during server's I/O loop, after received and sent all frames.
	 * </p>
	 * 
	 * @return {@code true} to mark this method did something significant so that
	 *         {@link Server} can keep running I/O loop instead of pausing thread
	 *         for a bit of time (which may introduces latency).
	 */
	protected boolean loopInServerThread() {
		return false;
	}

	protected void cleanInServerThread() {}

	public void handleRead(SocketChannel channel) throws IOException {
		if (readBuffer.remaining() > 0) {
			if (channel.read(readBuffer) == -1) return;
			if (readBuffer.remaining() > 0) return;
		}

		readBuffer.flip();
		switch (readMode) {
		case READMODE_HEADER:
			frameKind = readBuffer.getShort();
			bodySize = readBuffer.getShort();
			messageId = readBuffer.getInt();
			requestId = readBuffer.getLong();
			readMode = READMODE_BODY;
			readBuffer.clear().limit(bodySize);
			if (readBuffer.remaining() > 0) break;
		case READMODE_BODY:
			receiveFrame(frameKind, messageId, requestId, readBuffer);
			readMode = READMODE_HEADER;
			readBuffer.clear().limit(16);
			break;
		}
	}

	public void handleWrite(SocketChannel channel) throws IOException {
		// Flush pending
		if (writeBuffer.remaining() > 0) {
			channel.write(writeBuffer);
			if (writeBuffer.remaining() > 0) return;
		}

		OutgoingFrame frame;
		while ((frame = writeQueue.poll()) != null) {
			writeBuffer.clear()
				.putShort(0, frame.kind())
				.putShort(2, (short) 0)
				.putInt(4, frame.messageId())
				.putLong(8, frame.requestId())
				.position(16);
			frame.writer().accept(writeBuffer);
			writeBuffer.putShort(2, (short) (writeBuffer.position() - 16)).flip();
			channel.write(writeBuffer);
			if (writeBuffer.remaining() > 0) return; // Possibly can't write anymore
		}
	}

	public void writeFrame(short kind, int messageId, long requestId, Consumer<ByteBuffer> writer) {
		writeQueue.offer(new OutgoingFrame(kind, messageId, requestId, writer));
	}

	record OutgoingFrame(short kind, int messageId, long requestId, Consumer<ByteBuffer> writer) {
	}
}
