package io.github.nahkd123.stonks.utils.net;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.ByteChannel;
import java.util.Queue;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.function.Consumer;

public abstract class Connection {
	public static final short KIND_REQUEST = 0;
	public static final short KIND_RESPONSE_SUCCEED = 1;
	public static final short KIND_RESPONSE_FAILED = 2;
	public static final short KIND_NOTIFY = 3;

	private static final int READMODE_HEADER = 0;
	private static final int READMODE_BODY = 1;

	boolean running = true;
	boolean closeRequested = false;

	private ByteBuffer readBuffer;
	private int readMode = READMODE_HEADER;
	private short frameKind;
	private short bodySize;
	private int messageId;
	private long requestId;

	private ByteBuffer writeBuffer;
	private Queue<OutgoingFrame> writeQueue = new ConcurrentLinkedQueue<>();

	public Connection() {
		this.readBuffer = ByteBuffer.allocate(32767).limit(16);
		this.writeBuffer = ByteBuffer.allocate(32767).limit(0);
	}

	/**
	 * <p>
	 * Check whether the connection is being perceived as "running".
	 * </p>
	 */
	public boolean isRunning() { return running; }

	protected void setRunning(boolean running) { this.running = running; }

	public boolean isCloseRequested() { return closeRequested; }

	/**
	 * <p>
	 * Request the connection to be closed.
	 * </p>
	 */
	public void requestClose() {
		closeRequested = true;
	}

	/**
	 * <p>
	 * Called when received a frame from peer.
	 * </p>
	 * 
	 * @param kind      The kind of frame. Either of {@link #KIND_REQUEST},
	 *                  {@link #KIND_RESPONSE_SUCCEED},
	 *                  {@link #KIND_RESPONSE_FAILED} or {@link #KIND_NOTIFY}.
	 * @param messageId The ID of message. Message IDs are well-known between peers.
	 * @param requestId The request ID. This is generated by request peer.
	 * @param buffer    The buffer to read from.
	 */
	protected abstract void onFrameReceive(short kind, int messageId, long requestId, ByteBuffer buffer);

	/**
	 * <p>
	 * Called when the connection is being closed.
	 * </p>
	 * 
	 * @param isRemote Whether the connection is closed remotely.
	 */
	protected abstract void onConnectionClosing(boolean isRemote);

	public boolean handleRead(ByteChannel channel) throws IOException {
		boolean didSomething = false;
		if (!running || closeRequested) return didSomething;

		if (readBuffer.remaining() > 0) {
			int bytesRead = channel.read(readBuffer);

			if (bytesRead == -1) {
				running = false;
				onConnectionClosing(true);
				return didSomething;
			}

			didSomething |= bytesRead > 0;
			if (readBuffer.remaining() > 0) return didSomething;
		}

		readBuffer.flip();
		didSomething |= true;

		switch (readMode) {
		case READMODE_HEADER:
			frameKind = readBuffer.getShort();
			bodySize = readBuffer.getShort();
			messageId = readBuffer.getInt();
			requestId = readBuffer.getLong();
			readMode = READMODE_BODY;
			readBuffer.clear().limit(bodySize);
			if (readBuffer.remaining() > 0) break;
		case READMODE_BODY:
			onFrameReceive(frameKind, messageId, requestId, readBuffer);
			readMode = READMODE_HEADER;
			readBuffer.clear().limit(16);
			break;
		}

		return didSomething;
	}

	public boolean handleWrite(ByteChannel channel) throws IOException {
		boolean didSomething = false;
		if (!running || closeRequested) return didSomething;

		// Flush pending
		if (writeBuffer.remaining() > 0) {
			didSomething |= channel.write(writeBuffer) > 0;
			if (writeBuffer.remaining() > 0) return didSomething;
		}

		OutgoingFrame frame;
		while ((frame = writeQueue.poll()) != null) {
			writeBuffer.clear()
				.putShort(0, frame.kind())
				.putShort(2, (short) 0)
				.putInt(4, frame.messageId())
				.putLong(8, frame.requestId())
				.position(16);
			frame.writer().accept(writeBuffer);
			writeBuffer.putShort(2, (short) (writeBuffer.position() - 16)).flip();
			didSomething |= channel.write(writeBuffer) > 0;
			if (writeBuffer.remaining() > 0) return didSomething;
		}

		return didSomething;
	}

	public void writeFrame(short kind, int messageId, long requestId, Consumer<ByteBuffer> writer) {
		writeQueue.offer(new OutgoingFrame(kind, messageId, requestId, writer));
	}

	record OutgoingFrame(short kind, int messageId, long requestId, Consumer<ByteBuffer> writer) {
	}
}
