name: Build Documentations
on: 
  push:
    branches: [docs/1.20.x]
jobs:
  build:
    name: Build with mkdocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install mkdocs
        run: pip install -r requirements.txt
      - name: Build documentations
        run: mkdocs build
      - name: Upload pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: site
  deploy:
    name: Deploy documentations
    runs-on: ubuntu-latest
    needs: [build]
    permissions: 
      pages: write
      id-token: write
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v2
