name: Java CI with Gradle

on:
  push:
    branches: [ "main/1.20.x" ]
  pull_request:
    branches: [ "main/1.20.x" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.6.0
      with:
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: Fabric Mod Artifact
        path: fabric/build/libs/
