name: Java CI with Gradle

on:
  push:
    branches: [ "main/1.20.x", "next/1.20.x" ]
  pull_request:
    branches: [ "main/1.20.x", "next/1.20.x" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.6.0
      with:
        arguments: build
    - uses: actions/upload-artifact@v4
      with:
        name: Fabric Artifacts
        path: fabric/build/libs/
