name: Release on GitHub

on:
  push: 
    tags: [ "v*" ]
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Get current tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: Build with Gradle (Stonks version ${{ steps.tag.outputs.tag }})
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: |
            build
            -Pstonks_version=${{ steps.tag.outputs.tag }}
            --stacktrace
            --warning-mode=fail
      - uses: actions/upload-artifact@v3
        with:
          name: "stonks-fabric-${{ steps.tag.outputs.tag }}-release"
          path: fabric/build/libs/
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: true
          files: |
            */build/libs/*.jar
